name: Send Daily Blessing Email

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow if needed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  # Set the version of .NET you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish

    - name: Run the application to send the email
      run: |
        dotnet ./publish/DailyBlessingConsole.dll
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
  continue-on-error: true  # This will allow the workflow to continue even if this step fails.
    - name: Clean up
      run: |
        rm -rf ./publish  # Remove published files
